### ISSUE TITLE
Can not delete train jobs

### ISSUE THREAD

**Issue by simonschuang** [myelintek/web#2]
In this template /digits/templates/models/summary.html, delete_jobs() is not working.

**Comment by wewe0901** [comment]
@simonschuang 
After pull latest source in master branch and run service.
I saw some Error in train page it may relate to this issue.
Or we miss some file to push to repository

![2018-03-07 11 51 53](https://user-images.githubusercontent.com/2045106/37102319-9315bc72-2262-11e8-8dbf-092761059cf6.png)

**Comment by simonschuang** [comment]
can not delete dataset as well
<img width="958" alt="2018-03-09 10 17 05" src="https://user-images.githubusercontent.com/2860098/37187003-3816ffee-2383-11e8-9617-14894a3a05fc.png">

**Comment by wewe0901** [comment]
**Symptom**
Select data set and click delet it doesn't work.

**Root cause**
There is two reasons cause this issue.
1. after click delete it will show prompt to confirm this action, but the dialog has wrong css setting so its not visible.
2. after temptory fix this  issue by chroum debug tool, we get not permit error, we should input user name before perfrom delete action

**Solution**
1. if permission error redirect to login page
2. correct the bootbox prompt tool css settting.
    .modal backdrop-in { opacity: .5;}

**workaround**
1. goto <server.host>/login page enter username
2. afeter click 

I will fix it later.

**Comment by simonschuang** [comment]
use 'demo' as default username since we don't need authentication at this phase
