### ISSUE TITLE
new model page issues

### ISSUE THREAD

**Issue by simonschuang** [myelintek/web#57]
1. new model page shows all parameters
ex. bayesian runs option, RMS decay value.
![new_model](https://user-images.githubusercontent.com/2860098/44180112-43ece900-a12d-11e8-8037-5e425c92313a.png)

2. when clicking faster training configuration. no response.

**Comment by wewe0901** [comment]
**Symptom**
In "New Training" Page , Hyper-parameter configure page.  All Field are listed. But some or it should hide or show according to the policy. ex. bayesian runs option, RMS decay value.
 
**Root cause**
In the field display control javascript source, we use prefix match to get the fields with class starts with  hpo-specific. ex: $('[class^="prefix"]).  But I add a class "row" before the  hpo-specific-* class. So use prefix match can not get those element and control it. 

**workaround**
N/A

**solution**
not just use start with syntax, we use search syntax also
ex:  $('[class^="prefix"],[class*=" prefix"])
than we can get the prefix in class event it is not the first one
